# Generated by Django 4.1.5 on 2023-02-18 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='snippet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='MainApp.snippet'),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='lang',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='MainApp.lang'),
        ),
    ]
